better defaults

diff --git a/.config/git/hooks/pre-commit b/.config/git/hooks/pre-commit
--- a/.config/git/hooks/pre-commit
+++ b/.config/git/hooks/pre-commit
@@ -1,13 +1,20 @@
 #!/usr/bin/env bash
-set -e
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-if [ -f "composer.lock" -a -f ".php_cs.dist" ]; then
-    PHP_CS_FIXER="$(composer config bin-dir)/php-cs-fixer"
+# start templated
+INSTALL_PYTHON=/opt/homebrew/opt/pre-commit/libexec/bin/python3.11
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --skip-on-missing-config)
+# end templated
 
-    if [ -x "$PHP_CS_FIXER" ]; then
-        git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read -r line; do
-            php -C -n -d date.timezone=UTC "$PHP_CS_FIXER" fix --ansi --dry-run --verbose "${line}"
-        done
-    fi
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
+
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
+else
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
 fi
-
